USE krautundrueben;

DROP TABLE IF EXISTS REZEPTE;

CREATE TABLE REZEPTE (
    REZEPTNR        INTEGER NOT NULL,
    REZEPTNAME      VARCHAR,
    ZUTATEN         TEXT,
    ERNAERUNGSKATEGORIEN INTEGER NOT NULL,
    PRIMARY KEY (KUNDENNR)
);